name: Build and release artifacts

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y just
      - name: Build release artifact
        run: |
          just
      - name: Upload artifact (PR)
        if: github.ref != 'refs/heads/main'
        uses: mmkal/artifact.ci/upload@main
        with:
          name: be-bop-wizard
          path: dist/
          artifactci-visibility: public
          artifactci-mode: eager
      - name: Upload artifact (main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: be-bop-wizard
          path: dist/
  release:
    name: Create GitHub Release
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download built artifact
        uses: actions/download-artifact@v4
        with:
          path: release_artifacts
          merge-multiple: true
      - name: Get merge commit message
        id: commit
        run: |
          TITLE=$(git log -1 --pretty=%s)
          BODY=$(git log -1 --pretty=%b)
          COMMIT_DATE="$(git log -1 --date=format:%F --pretty=format:%cd)"
          HASH=$(git rev-parse --short HEAD)
          echo "title<<EOF" >> $GITHUB_OUTPUT
          echo "$TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "commit_date=$COMMIT_DATE" >> $GITHUB_OUTPUT
          echo "hash=$HASH" >> $GITHUB_OUTPUT
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: rel/${{ steps.commit.outputs.commit_date }}/${{ steps.commit.outputs.hash }}
          name: ${{ steps.commit.outputs.title }}
          body: ${{ steps.commit.outputs.body }}
          files: |
            release_artifacts/be-bop-wizard.sh
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
